### ISSUE TITLE
iOS "plays" but no audio comes out

### ISSUE THREAD

**Issue by CesarOliveira** [arielfaur/ionic-audio#90]
In my iOS the application plays, but I don't hear any audio.

Works fine in the browser, but when I build on iOS and run from XCode, no audio come out.

In XCode shows the audio is playing: 
![screen shot 2017-02-04 at 4 32 04 pm](https://cloud.githubusercontent.com/assets/6030005/22620656/8d039046-eaf7-11e6-80bf-40a8dfb34f45.png)

In iOS the time "runs" normaly, but no audio comes out
![img_2726](https://cloud.githubusercontent.com/assets/6030005/22620670/eb70f02e-eaf7-11e6-97bd-0cad40b5c2ac.PNG)

Any Ideas?

**Comment by arielfaur** [comment]
Have you been able to solve this? I just pushed an updated version that works with Ionic 2. I don't think this will fix your iOS issue, but you might want to give it a try

Updated documentation:
http://arielfaur.github.io/ionic-audio/2.0/index.html

**Comment by CesarOliveira** [comment]
Not yet, I'm runing some tests

**Comment by CesarOliveira** [comment]
Still not working, I get the new version,  but  the no audio comes out in my iPhone, any ideas?

**Comment by arielfaur** [comment]
It is weird because it seems the audio files are being loaded and the progress bar displayed.

**Comment by CesarOliveira** [comment]
Yep, I don't understand neither

**Comment by arielfaur** [comment]
Can you check the javascript console with remote debugging? See if there is an error there. Also, check whether it using the web provider or Cordova Media.

**Comment by borodiliz** [comment]
Not tested on iPhone yet, but audio works for me on iPad 2 with IOS v9.3.5

**Comment by CesarOliveira** [comment]
No error in the log, take a look:

2017-02-17 10:04:35.953853 mobile-app2[378:38754] DiskCookieStorage changing policy from 2 to 0, cookie file: file:///private/var/mobile/Containers/Data/Application/3D51650A-CF12-44FF-92EB-CBF9B88A8E34/Library/Cookies/Cookies.binarycookies
2017-02-17 10:04:36.062178 mobile-app2[378:38754] Apache Cordova native platform version 4.1.1 is starting.
2017-02-17 10:04:36.063534 mobile-app2[378:38754] Multi-tasking -> Device: YES, App: YES
2017-02-17 10:04:36.174187 mobile-app2[378:38754] Using UIWebView
2017-02-17 10:04:36.178074 mobile-app2[378:38754] [CDVTimer][handleopenurl] 0.150025ms
2017-02-17 10:04:36.181642 mobile-app2[378:38754] [CDVTimer][intentandnavigationfilter] 3.383994ms
2017-02-17 10:04:36.181992 mobile-app2[378:38754] [CDVTimer][gesturehandler] 0.172973ms
2017-02-17 10:04:36.211133 mobile-app2[378:38754] [CDVTimer][splashscreen] 28.986990ms
2017-02-17 10:04:36.232113 mobile-app2[378:38754] [CDVTimer][statusbar] 20.717978ms
2017-02-17 10:04:36.235394 mobile-app2[378:38754] [CDVTimer][keyboard] 3.013968ms
2017-02-17 10:04:36.263075 mobile-app2[378:38754] [CDVTimer][file] 27.471006ms
2017-02-17 10:04:36.263246 mobile-app2[378:38754] [CDVTimer][TotalPluginStartup] 85.413992ms
2017-02-17 10:04:36.916928 mobile-app2[378:38754] Resetting plugins due to page load.
2017-02-17 10:04:41.288512 mobile-app2[378:38754] Finished load of: file:///var/containers/Bundle/Application/36151DA5-DE65-4E9C-8EAA-EAC6145511C3/mobile-app2.app/www/index.html
2017-02-17 10:04:41.459737 mobile-app2[378:38754] DEVICE READY FIRED AFTER 3493 ms
2017-02-17 10:04:45.674588 mobile-app2[378:38754] Loading track http://s3.amazonaws.com/poadcastapp/poadcasts/alcanceconquiste/media_1.mp3
2017-02-17 10:04:45.796903 mobile-app2[378:38754] Loaded track http://s3.amazonaws.com/poadcastapp/poadcasts/alcanceconquiste/media_1.mp3
2017-02-17 10:04:45.797068 mobile-app2[378:38754] Playing track http://s3.amazonaws.com/poadcastapp/poadcasts/alcanceconquiste/media_1.mp3
2017-02-17 10:16:30.925838 mobile-app2[378:38754] Pausing track http://s3.amazonaws.com/poadcastapp/poadcasts/alcanceconquiste/media_1.mp3

**Comment by arielfaur** [comment]
So where is it not working? Before you said it is not working on iPhone. And you just said you have not tested on iPhone yet. What is it then? 😄

**Comment by CesarOliveira** [comment]
I tested on iPhone, but no audio comes out. Above is the log of my Xcode when I run on my Iphone.

When I press "Play", in the console show this: 2017-02-17 10:04:45.796903 mobile-app2[378:38754] Loaded track http://s3.amazonaws.com/poadcastapp/poadcasts/alcanceconquiste/media_1.mp3

The progress bar start moving, but no audio comes out.

**Comment by arielfaur** [comment]
I will try to test on iOS 10 and get back to you

**Comment by CesarOliveira** [comment]
I get another iPhone to test here, seems like a problem in mine

**Comment by CesarOliveira** [comment]
I will investigate it in tell you what  happened.
